{
 "title": "Celery - Workers & Queues",
 "tags": [
  "celery",
  "monitoring",
  "workers",
  "beat"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Number Of Active Workers",
   "type": "graph",
   "description": "This panel shows the number of active workers under Celery",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_active_workers" }
   ]
  },
  {
   "title": "Active Worker Status",
   "type": "graph",
   "description": "This panel shows the amount of time a celery worker is alive",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "worker_uptime" }
   ]
  },
  {
   "title": "Num Active Queues",
   "type": "graph",
   "description": "This panel shows the number of active queues under a celery worker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_queues", "legendFormat": "{{ worker }}" }
   ]
  }
 ]
}